
wandb:
  project: "osg-testing"
  log_to_wandb: true

training:
  epochs: 1000
  eval_freq: 10 
  learning_rate: 0.001
  batch_size: 64

model:
  type: "random"
  model_specific_param: 1.0  # Example of a model-specific parameter

dataset:
  env_name: "halfcheetah-expert-v2"
  path: "path/to/your/dataset"

target:
  target_percentile: 90 
  target_len: 50 
